### PR TITLE
(feat) update development branch to PyQT5, Python-3.5 & 3.5, tables-3.4 API

### LINKED ISSUE #40: PyQt5 support ?
Does ViTables intend to support Qt5  ?

### LINKED ISSUE #49: Python 3.5 support?
Is there a way to install ViTables on a Python 3.5 linux machine? Thanks!

### PR DESCRIPTION
**Pull request by ankostis**
+ Base on `development` branch and upon pre-existing branches from other contributors to bring up-to-date with:
  +  Qt5  (FIX #40), 
  + Python-3.5 & 3.6 (FIX #49), and 
  + table-3.4+ API (cherry-pick #58).
+ Minor enhancements to UIs (i.e. rename group proposes existing name)
+ Tested on WinPython-64bit-3.5.3.0Qt5.

### CODE REVIEW

**Comment by ankostis** [comment]
@uvemas what do you advise me to do here?

Should I merge my QT5 "pip-install-n-launch" branch with master?

**Comment by ankostis** [comment]
@alexey-naydenov  any idea here how to proceed?

**Comment by uvemas** [comment]
Thanks a lot for your great help. I'll add you to the contributors list ASAP (or maybe I should include you as a main developer :)

**Comment by ankostis** [comment]
Thank you, I'm flattered.
But as I said, most of the work was there by others.

Let's not hurry - I doubt that I can find the time to work on this project, regularly.

**Comment by stonebig** [comment]
hum, with latest master, when launching from spyder menu, vitables "splash screen" works, but  then nothing. did you try that @ankostis  ?

**Comment by stonebig** [comment]
ok, i found the way:
````
vitables -v 2 -l "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\notebooks\vit.log"
````

**Pull request merged**
