### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by m3lab-zzl**
For issue #121 

- Change `.txt` to `.rst`
- Add badges
- Add screenshots to show how vitables looks like.

This is just a draft, feel free to revise.

Cheers 🍻

### CODE REVIEW

**Comment by uvemas** [comment]
Looks great! In my opinion the header (logo + badges + logo) is too large, but it is a matter of taste. So do it as you prefer.

CU!

**Comment by m3lab-zzl** [comment]
> What's the point of the FAQ suggested fix? I mean, why not fix the code in the first place?

Feel free to add more questions and answers, I only wrote one in this draft. If you prefer, we could get rid of FAQ for this version.

**Comment by m3lab-zzl** [comment]
> Looks great! In my opinion the header (logo + badges + logo) is too large, but it is a matter of taste. So do it as you prefer.
> 
> CU!

Hi @uvemas,  I saw the first logo (the larger one) in `doc/images`, and the second one in vitables.org. I like them both, but it may be a good idea to select ONLY one. Again, feel free to revise the draft.

**Comment by uvemas** [comment]
@ankostis the problem was fixed in the repo some time ago but I haven't released new versions since Dec. 2019. I'm in the process of publishing the new minor release ASAP. So if @m3lab-zzl removes the mention to Iterable the document will be just fine IMHO.

**Pull request merged**
