### PR TITLE
Use QtPy abstraction layer for PyQt5/PyQt4/PySide

### LINKED ISSUE #62: move to (vendored or not) QtPy
a move of Pytables off from a direct Qt interface to an indirect "QtPy" would make it:
- usable for PyQt4/PyQt5/PySide2.
- more resistant to another Qt version change.

### PR DESCRIPTION
**Pull request by cgohlke**
Fix #62

Seems to work for me with QtPy-1.2.1 and PyQt4-4.11.4 on Python 3.6, Windows 10.

I put a wheel at http://www.lfd.uci.edu/~gohlke/pythonlibs/#vitables if anyone want to try.

### CODE REVIEW

**Comment by stonebig** [comment]
your wheel works on python-3.6.1 PyQt-5.8.2, but there seems not to start  on Python 64bit 3.5.3 with:
- PyQt4 (4.11.4)
- QtPy (1.2.1)

**Comment by cgohlke** [comment]
> but Vitables seems not to start on Python 64 bit 3.5.3 with

Works for me with exactly the same versions.

Try `python -c"import vitables.start;vitables.start.gui()"` to see the traceback, if any.

**Comment by stonebig** [comment]
hum .... this may be my fault, but I  have to figure out why:
````
C:\WinPython\basedir35\build\winpython-64bit-3.5.x.1\scripts>python -c"import vitables.start;vitables.start.gui()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\WinPython\basedir35\build\winpython-64bit-3.5.x.1\python-3.5.3.amd64\lib\site-packages\vitables\start.py", line 34, in <module>
    from PyQt5 import QtGui
ImportError: No module named 'PyQt5'````

**Comment by uvemas** [comment]
Thanks a lot for the PR.

**Pull request merged**
