### PR TITLE
WIP: FIX #42: start table index/columns from 0 (python-like)

### LINKED ISSUE #42: Add option to make the row numbers start at 0
Since indexes in Python also start at 0 it would be easier if the row numbering in ViTables also allows for row numbering that start at 0.

### PR DESCRIPTION
**Pull request by ankostis**
It does not offer the possibility to configure it as a preference.

### CODE REVIEW

**Comment by uvemas** [comment]
Not sure about this feature. Most of users seem to be happy with one based rows.

**Comment by ankostis** [comment]
OK, should make it preferences configurable, because for pythoners (and [some others](http://www.cs.utexas.edu/users/EWD/ewd08xx/EWD831.PDF)[1]), it really does make sense to start counting from zero.

[1] http://stackoverflow.com/a/13519429/548792

**Comment by uvemas** [comment]
OK. You've convinced me with that nice SO thread.

**Comment by ankostis** [comment]
Well, I didn't find that convincing SO's explanation.
What really had persuaded me many years ago about this matter was Dykstra's hand-written paper(the 1st link above).  I enjoyed particularly following his robust thread of thought :-)

**Comment by uvemas** [comment]
Sorry, I missed that. A great paper indeed. Thanks for let me know about it.

**Pull request merged**
