### PR TITLE
release v3.0.3

### PR DESCRIPTION
**Pull request by StFroese**
@uvemas I just prepared a small patch release :) it basically just includes the support for pyqt6. Feel free to comment for changes

### CODE REVIEW

**Comment by uvemas** [comment]
Thanks for your help @StFroese!

**Comment by StFroese** [comment]
@uvemas No problem :) Can you release this on pypi? :)

**Comment by uvemas** [comment]
Yes, I'll try to do it ASAP.

**Comment by uvemas** [comment]
@StFroese finally I've published the 3.0.3 release on PyPI. Only one significant change, Packaging tool is not setuptools but hatch. So setup.py has been replaced with pyproject.toml.

**Comment by StFroese** [comment]
@uvemas thanks a lot, I published it to conda-forge :)

**Pull request merged**
