### PR TITLE
Track data files without requiring setuptools-git

### LINKED ISSUE #33: installing the develop branch
I wanted to try the develop branch, but, as of today (71504a3c478) it does not run...
`python setup.py install` seem to work but it does not copy the .ui files, so I am left with a broken copy.

### PR DESCRIPTION
**Pull request by kprussing**
Fixes #33.  This was accidentally opened as #43 which is now closed.

As discussed in uvemas/ViTables#33, the data files for the development
branch are not tracked unless the user has setuptools-git installed.
However, it is not guaranteed that all users will have this requirement
as not all end users are necessarily developers or have the proper git
tools installed.  This patch adds a function to the setup.py script to
traverse the packages and locate data files in all subdirectories that
are not subpackages.  Data files are assumed to be all files that are
not Python files (.py and .pyc).

### CODE REVIEW

**Comment by alexey-naydenov** [comment]
Hi,
Replacing setuptools-git with custom script does not seem like a clean solution to me. I agree that requiring git (through setuptools-git) in order to use vitables is not very nice either. I think there are 2 better alternatives: use manifest.in or create linux packages. Manifest file can be created using some script.

**Comment by kprussing** [comment]
I agree that a custom script like this may not be the cleanest solution.  I can think of a few ways that erroneous files could be included in the install.  Looking at the [documentation for setup tools](https://pythonhosted.org/setuptools/setuptools.html#including-data-files), the MANIFEST.in file is the commonly recommended way to go.  Looking at the project, I thought the move away from the MANIFEST.in to dynamically detecting the included files was desired; thus, I wrote the script.  I attempted to use the `package_data` keyword to setup, but I could not get the globbing to properly discover all of the necessary files. I can go back and rework parts to generate the MANIFEST.in, or I can just write the file.

You guys have done a great job with ViTables, and I know your schedules are busy.  I'm just lucky that the project I'm working on at the moment allows me to put a bit of effort into helping.

**Comment by kprussing** [comment]
I got a chance to take another look at using the MANIFEST.in and the `package_data` keyword.  The issue with the globbing using `package_data` was due to my misunderstanding of what it will find.  Using this method, the change reduces to just four lines.  You can see the changes I made [on this branch](https://github.com/kprussing/ViTables/tree/alt_inst_fix).  

I won't bother initiating another pull request if you have different solution you prefer because I don't want to spam the issues with superfluous pull requests.

**Comment by kprussing** [comment]
Using the Manifest file is the cleaner solution.  Attempting to use the `package_data` keyword to the setup function does [not always recursively track the data files](http://blog.klinsight.com/2012/08/setuptools-includepackagedata-does-not.html).  I encountered this creating a source distribution for my colleagues.  My final solution was to just use the following two lines in the Manifest file.

    include *.pro *.txt *.ts VERSION
    recursive-include vitables *.ico *.ini *.png *.qm *.svg *.ui

**Pull request closed without merging**
